const ROLES = Object.freeze({ CUSTOMER: 'CUSTOMER', BANK_ADMIN: 'BANK_ADMIN', BANK_STAFF: 'BANK_STAFF' });
const ACCOUNT_STATUS = Object.freeze({ PENDING: 'PENDING', ACTIVE: 'ACTIVE', FROZEN: 'FROZEN', CLOSED: 'CLOSED' });
const ACCOUNT_TYPES = Object.freeze({ SAVINGS: 'SAVINGS', CURRENT: 'CURRENT' });
const TRANSACTION_TYPES = Object.freeze({ DEPOSIT: 'DEPOSIT', WITHDRAWAL: 'WITHDRAWAL', TRANSFER: 'TRANSFER', BILL_PAYMENT: 'BILL_PAYMENT', REFUND: 'REFUND', REVERSAL: 'REVERSAL', FEE: 'FEE' });
const TRANSACTION_STATUS = Object.freeze({ PENDING: 'PENDING', PROCESSING: 'PROCESSING', COMPLETED: 'COMPLETED', FAILED: 'FAILED', CANCELLED: 'CANCELLED', REVERSED: 'REVERSED' });
const ORDERED_TRANSITIONS = {
  PENDING: ['PROCESSING', 'FAILED', 'CANCELLED'],
  PROCESSING: ['COMPLETED', 'FAILED'],
  COMPLETED: ['REVERSED'],
  FAILED: [],
  CANCELLED: [],
  REVERSED: []
};
module.exports = { ROLES, ACCOUNT_STATUS, ACCOUNT_TYPES, TRANSACTION_TYPES, TRANSACTION_STATUS, ORDERED_TRANSITIONS };
